CREATE TABLE IF NOT EXISTS users (
       id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
       timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
       username TEXT NOT NULL UNIQUE,
       password TEXT NOT NULL);


ALTER TABLE users ADD COLUMN role_id INTEGER NOT NULL REFERENCES users_roles(id);
       
