CREATE TABLE IF NOT EXISTS users (
       id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
       timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
       username TEXT NOT NULL,
       password TEXT NOT NULL);	
       
